name: .NET

on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Hello message
      run: echo "Hello guys"

  BuildProject:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - run: dotnet build ActionsKataExample