name: .NET

on: 
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Hello message
      run: echo "Hello guys"
    steps:
    - task: UseDotNet@2
      inputs:
        version: '6.x'
  BuildProject:
    runs-on: windows-latest

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'